
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class Account_frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Account_frame
     */
     private Connection con =null;
     private PreparedStatement ps = null;
     private ResultSet rs = null;
     DefaultTableModel model;
     String no ="ID";
     String fname = "FirstName";
     String lname = "LastName";
     String status = "access";
     String date = "date_created";
     
    public Account_frame() {
        initComponents();
        
         con = MySqlConnect.ConnectDB();
         model =(DefaultTableModel) accountTable.getModel();
         getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Account_frame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        changeB = new javax.swing.JButton();
        closeB = new javax.swing.JButton();

        setClosable(true);
        setTitle("Accounts");

        Account_frame.setBackground(new java.awt.Color(204, 204, 204));

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No", "Name", "Status", "Date Created"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accountTable);

        changeB.setBackground(new java.awt.Color(255, 255, 153));
        changeB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        changeB.setText("Change");
        changeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBActionPerformed(evt);
            }
        });

        closeB.setBackground(new java.awt.Color(255, 255, 153));
        closeB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        closeB.setText("Close");
        closeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Account_frameLayout = new javax.swing.GroupLayout(Account_frame);
        Account_frame.setLayout(Account_frameLayout);
        Account_frameLayout.setHorizontalGroup(
            Account_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(Account_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Account_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Account_frameLayout.createSequentialGroup()
                    .addContainerGap(467, Short.MAX_VALUE)
                    .addComponent(closeB)
                    .addGap(22, 22, 22)))
        );
        Account_frameLayout.setVerticalGroup(
            Account_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Account_frameLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(changeB)
                .addContainerGap())
            .addGroup(Account_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Account_frameLayout.createSequentialGroup()
                    .addContainerGap(303, Short.MAX_VALUE)
                    .addComponent(closeB)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Account_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Account_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(300, 0, 572, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void changeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBActionPerformed
        // TODO add your handling code here:
          DisplayStockData s = new   DisplayStockData();
          int index =  accountTable.getSelectedRow();
          no = model.getValueAt(index, 0).toString();
          
          
          s.empStatus(no);
          ChangeEmpStatus_frame ce  = new ChangeEmpStatus_frame();
          
         // JOptionPane.showMessageDialog(null, s.status);
       

    }//GEN-LAST:event_changeBActionPerformed

    private void closeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeBActionPerformed

    private void accountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountTableMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_accountTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account_frame;
    private javax.swing.JTable accountTable;
    private javax.swing.JButton changeB;
    private javax.swing.JButton closeB;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void getData() 
    {
        
         try {
             ps = con.prepareStatement("Select * from employee");
             
             rs =ps.executeQuery();
             
             while(rs.next())
             {
                 
                  no = rs.getString("ID");
                  fname = rs.getString("FirstName");
                  lname = rs.getString("LastName");
                  status = rs.getString("access");
                  date = rs.getString("date_created");
                 
                 
                 model.insertRow( model.getRowCount(), new Object[]{no,fname+" "+lname,status,date});
             }
         } catch (SQLException ex) {
             Logger.getLogger(Account_frame.class.getName()).log(Level.SEVERE, null, ex);
         }
             
        
       
        finally
        {
                try 
                {
                    rs.close();
                    ps.close();
                    con.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(Inbox_frame.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
    }
    
    
    public void changeStatus()
    {
        
        
        JOptionPane.showMessageDialog(null,""+no+"");
        
    }
}
