
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class Alert_setup extends javax.swing.JFrame {

    /**
     * Creates new form Alert_setup
     */
    public Alert_setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupPanel = new javax.swing.JPanel();
        productNoL = new javax.swing.JLabel();
        productNoTF = new javax.swing.JTextField();
        quantityL = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        plusB = new javax.swing.JButton();
        minusB = new javax.swing.JButton();
        saveB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        productNameL = new javax.swing.JLabel();
        productNameTF = new javax.swing.JTextField();
        vendorL = new javax.swing.JLabel();
        vendorTF = new javax.swing.JTextField();
        unitPriceL = new javax.swing.JLabel();
        retailPriceL = new javax.swing.JLabel();
        unitPriceTF = new javax.swing.JTextField();
        retailPriceTF = new javax.swing.JTextField();
        documentNoL = new javax.swing.JLabel();
        documentNoTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setupPanel.setBackground(new java.awt.Color(204, 204, 204));

        productNoL.setText("Product No.");

        productNoTF.setEditable(false);
        productNoTF.setBackground(new java.awt.Color(204, 204, 255));
        productNoTF.setText(" ");

        quantityL.setText("Minimum Stock Quantity");

        quantityTF.setBackground(new java.awt.Color(255, 255, 153));
        quantityTF.setText("1");

        plusB.setBackground(new java.awt.Color(255, 255, 153));
        plusB.setText("+");
        plusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBActionPerformed(evt);
            }
        });

        minusB.setBackground(new java.awt.Color(255, 255, 153));
        minusB.setText("-");
        minusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBActionPerformed(evt);
            }
        });

        saveB.setBackground(new java.awt.Color(255, 255, 153));
        saveB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        cancelB.setBackground(new java.awt.Color(255, 255, 153));
        cancelB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        productNameL.setText("Product Name");

        productNameTF.setEditable(false);
        productNameTF.setBackground(new java.awt.Color(204, 204, 255));
        productNameTF.setText(" ");

        vendorL.setText("Vendor");

        vendorTF.setEditable(false);
        vendorTF.setBackground(new java.awt.Color(204, 204, 255));
        vendorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorTFActionPerformed(evt);
            }
        });

        unitPriceL.setText("Unit Price");

        retailPriceL.setText("Retail Price");

        unitPriceTF.setEditable(false);
        unitPriceTF.setBackground(new java.awt.Color(204, 204, 255));
        unitPriceTF.setText("0.00");

        retailPriceTF.setEditable(false);
        retailPriceTF.setBackground(new java.awt.Color(204, 204, 255));
        retailPriceTF.setText("0.00");

        documentNoL.setText("Document No.");

        documentNoTF.setEditable(false);
        documentNoTF.setBackground(new java.awt.Color(204, 204, 255));
        documentNoTF.setText("01");

        javax.swing.GroupLayout setupPanelLayout = new javax.swing.GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(saveB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plusB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minusB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(productNoL)
                                .addGap(231, 231, 231))
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(setupPanelLayout.createSequentialGroup()
                                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(productNameL)
                                            .addComponent(vendorL))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(productNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                            .addComponent(productNameTF)
                                            .addComponent(vendorTF)))
                                    .addComponent(quantityL))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(setupPanelLayout.createSequentialGroup()
                                        .addComponent(retailPriceL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(retailPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(setupPanelLayout.createSequentialGroup()
                                        .addComponent(unitPriceL)
                                        .addGap(32, 32, 32)
                                        .addComponent(unitPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70))
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addComponent(documentNoL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(documentNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        setupPanelLayout.setVerticalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNoL)
                            .addComponent(productNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitPriceL)
                            .addComponent(unitPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameL)
                    .addComponent(productNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retailPriceL)
                    .addComponent(retailPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorL)
                    .addComponent(vendorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentNoL)
                    .addComponent(documentNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(quantityL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusB)
                    .addComponent(minusB))
                .addGap(22, 22, 22)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveB)
                    .addComponent(cancelB))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void plusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBActionPerformed
        // TODO add your handling code here:
        int count = Integer.parseInt(quantityTF.getText());
        try{
            count++;
            quantityTF.setText(""+count);
        }
        catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null,"SYSTEM ERROR! /n Numbers Only ");
        }
    }//GEN-LAST:event_plusBActionPerformed

    private void minusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBActionPerformed
        // TODO add your handling code here:
        int count = Integer.parseInt(quantityTF.getText());

        try{
            if(count>0)
            count--;

            quantityTF.setText(""+count);
        }
        catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null,"SYSTEM ERROR! /n Numbers Only ");
        }
    }//GEN-LAST:event_minusBActionPerformed

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        // TODO add your handling code here:
         int a =JOptionPane.showConfirmDialog(null,"Save Changes?","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

        if(a ==0){
              JOptionPane.showMessageDialog(null,"Alert Saved!");
              setVisible(false);
        }
        
    }//GEN-LAST:event_saveBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"All unsaved data will be lost","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

        if(a ==0){
              setVisible(false);
        }
    }//GEN-LAST:event_cancelBActionPerformed

    private void vendorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorTFActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel documentNoL;
    private javax.swing.JTextField documentNoTF;
    private javax.swing.JButton minusB;
    private javax.swing.JButton plusB;
    private javax.swing.JLabel productNameL;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JLabel productNoL;
    private javax.swing.JTextField productNoTF;
    private javax.swing.JLabel quantityL;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JLabel retailPriceL;
    private javax.swing.JTextField retailPriceTF;
    private javax.swing.JButton saveB;
    private javax.swing.JPanel setupPanel;
    private javax.swing.JLabel unitPriceL;
    private javax.swing.JTextField unitPriceTF;
    private javax.swing.JLabel vendorL;
    private javax.swing.JTextField vendorTF;
    // End of variables declaration//GEN-END:variables
}
