
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class Alerts_frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alerts_frame
     */
    public Alerts_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        alertPanel = new javax.swing.JPanel();
        productNoL = new javax.swing.JLabel();
        productNoTF = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        quantityL = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        nextB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        productNameL = new javax.swing.JLabel();
        productNameTF = new javax.swing.JTextField();
        vendorL = new javax.swing.JLabel();
        vendorTF = new javax.swing.JTextField();
        unitPriceL = new javax.swing.JLabel();
        retailPriceL = new javax.swing.JLabel();
        unitPriceTF = new javax.swing.JTextField();
        retailPriceTF = new javax.swing.JTextField();
        totalL = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        documentNoL = new javax.swing.JLabel();
        documentNoTF = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Set-up Alerts");

        alertPanel.setBackground(new java.awt.Color(204, 204, 204));

        productNoL.setText("Product No.");

        productNoTF.setBackground(new java.awt.Color(255, 255, 153));
        productNoTF.setText(" ");

        searchB.setBackground(new java.awt.Color(255, 255, 153));
        searchB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        searchB.setText("Search");

        quantityL.setText("InStock");

        quantityTF.setEditable(false);
        quantityTF.setBackground(new java.awt.Color(204, 204, 255));
        quantityTF.setText("1");

        nextB.setBackground(new java.awt.Color(255, 255, 153));
        nextB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nextB.setText("Next");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });

        cancelB.setBackground(new java.awt.Color(255, 255, 153));
        cancelB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        productNameL.setText("Product Name");

        productNameTF.setEditable(false);
        productNameTF.setBackground(new java.awt.Color(204, 204, 255));
        productNameTF.setText(" ");

        vendorL.setText("Vendor");

        vendorTF.setEditable(false);
        vendorTF.setBackground(new java.awt.Color(204, 204, 255));
        vendorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorTFActionPerformed(evt);
            }
        });

        unitPriceL.setText("Unit Price");

        retailPriceL.setText("Retail Price");

        unitPriceTF.setEditable(false);
        unitPriceTF.setBackground(new java.awt.Color(204, 204, 255));
        unitPriceTF.setText("0.00");

        retailPriceTF.setEditable(false);
        retailPriceTF.setBackground(new java.awt.Color(204, 204, 255));
        retailPriceTF.setText("0.00");

        totalL.setText("Total order amount");

        totalTF.setEditable(false);
        totalTF.setBackground(new java.awt.Color(204, 204, 255));
        totalTF.setText("0.00");

        documentNoL.setText("Document No.");

        documentNoTF.setEditable(false);
        documentNoTF.setBackground(new java.awt.Color(204, 204, 255));
        documentNoTF.setText("01");

        javax.swing.GroupLayout alertPanelLayout = new javax.swing.GroupLayout(alertPanel);
        alertPanel.setLayout(alertPanelLayout);
        alertPanelLayout.setHorizontalGroup(
            alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertPanelLayout.createSequentialGroup()
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alertPanelLayout.createSequentialGroup()
                                .addComponent(totalL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(alertPanelLayout.createSequentialGroup()
                                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameL)
                                    .addComponent(vendorL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vendorTF)
                                    .addComponent(productNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(productNoTF, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(productNoL))
                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alertPanelLayout.createSequentialGroup()
                                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(alertPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(retailPriceL)
                                            .addComponent(unitPriceL)))
                                    .addGroup(alertPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(searchB)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(25, 25, 25))
                            .addGroup(alertPanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(quantityL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alertPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(documentNoL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retailPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(documentNoTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(quantityTF, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(47, 47, 47))
            .addGroup(alertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alertPanelLayout.setVerticalGroup(
            alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertPanelLayout.createSequentialGroup()
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(productNoL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alertPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameL)
                    .addComponent(productNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitPriceL)
                    .addComponent(unitPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorL)
                    .addComponent(vendorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retailPriceL)
                    .addComponent(retailPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(documentNoL)
                    .addComponent(documentNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalL)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(alertPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(alertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextB)
                    .addComponent(cancelB))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alertPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(300, 0, 573, 346);
    }// </editor-fold>//GEN-END:initComponents

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
        // TODO add your handling code here:
       Alert_setup run =new Alert_setup();
        
        run.setVisible(true);
    }//GEN-LAST:event_nextBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"All unsaved data will be lost","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

                if(a ==0){
                    
                     setVisible(false);
                   }
    }//GEN-LAST:event_cancelBActionPerformed

    private void vendorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alertPanel;
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel documentNoL;
    private javax.swing.JTextField documentNoTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nextB;
    private javax.swing.JLabel productNameL;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JLabel productNoL;
    private javax.swing.JTextField productNoTF;
    private javax.swing.JLabel quantityL;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JLabel retailPriceL;
    private javax.swing.JTextField retailPriceTF;
    private javax.swing.JButton searchB;
    private javax.swing.JLabel totalL;
    private javax.swing.JTextField totalTF;
    private javax.swing.JLabel unitPriceL;
    private javax.swing.JTextField unitPriceTF;
    private javax.swing.JLabel vendorL;
    private javax.swing.JTextField vendorTF;
    // End of variables declaration//GEN-END:variables
}
