import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class Delivery_frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Delivery_frame
     */
    private Connection con =null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    DefaultTableModel model;
    public static  String no="",pId="",quantity="",total="", pname="";
    
    public Delivery_frame() {
        initComponents();
         setTitle("Delivery");
         con = MySqlConnect.ConnectDB();
         model =(DefaultTableModel) orderTable.getModel();
         getData();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNoTF = new javax.swing.JPasswordField();
        productCodeL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        saveB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        searchB = new javax.swing.JButton();
        totalPriceL = new javax.swing.JLabel();
        totalPriceTF = new javax.swing.JTextField();
        deliveredL = new javax.swing.JLabel();
        deliveredTF = new javax.swing.JTextField();
        plusB = new javax.swing.JButton();
        minusB = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        productNoTF.setBackground(new java.awt.Color(255, 255, 153));

        productCodeL.setText("Product No.");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Document No.", "Product Name", "Product Code", "Quantity", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);

        saveB.setBackground(new java.awt.Color(255, 255, 153));
        saveB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        cancelB.setBackground(new java.awt.Color(255, 255, 153));
        cancelB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        searchB.setBackground(new java.awt.Color(255, 255, 153));
        searchB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        searchB.setText("Search");

        totalPriceL.setText("Total Price");

        totalPriceTF.setEditable(false);
        totalPriceTF.setBackground(new java.awt.Color(204, 204, 255));
        totalPriceTF.setText("0.00");

        deliveredL.setText("Delivered Quantity");

        deliveredTF.setBackground(new java.awt.Color(255, 255, 153));
        deliveredTF.setText("0");

        plusB.setBackground(new java.awt.Color(255, 255, 153));
        plusB.setText("+");
        plusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBActionPerformed(evt);
            }
        });

        minusB.setBackground(new java.awt.Color(255, 255, 153));
        minusB.setText("-");
        minusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveB)
                        .addGap(18, 18, 18)
                        .addComponent(cancelB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPriceL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productCodeL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(totalPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deliveredL)
                        .addGap(18, 18, 18)
                        .addComponent(deliveredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plusB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCodeL)
                    .addComponent(productNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveredL)
                    .addComponent(deliveredTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusB)
                    .addComponent(minusB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPriceL)
                    .addComponent(totalPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelB)
                    .addComponent(saveB))
                .addGap(26, 26, 26))
        );

        setBounds(300, 0, 494, 355);
    }// </editor-fold>//GEN-END:initComponents

    private void minusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBActionPerformed
        // TODO add your handling code here:
         int count = Integer.parseInt(deliveredTF.getText());
        try{
        count--;
        deliveredTF.setText(""+count);
        }
        catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null,"SYSTEM ERROR! /n Numbers Only ");
        }
    }//GEN-LAST:event_minusBActionPerformed

    private void plusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBActionPerformed
        // TODO add your handling code here:
         int count = Integer.parseInt(deliveredTF.getText());
        try{
        count++;
        deliveredTF.setText(""+count);
        }
        catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null,"SYSTEM ERROR! /n Numbers Only ");
        }
    }//GEN-LAST:event_plusBActionPerformed

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"All unsaved data will be lost","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

                if(a ==0){
                    
                     setVisible(false);
                   }
    }//GEN-LAST:event_cancelBActionPerformed
    
    public void getData(){
        
        DisplayStockData s = new DisplayStockData();
        try
        {    
    
             ps = con.prepareStatement("Select * from prod_order");
             
             rs =ps.executeQuery();
             
             while(rs.next())
             {
                
                 no = rs.getString("ID");
                 pId = rs.getString("prod_id");
                 quantity = rs.getString("quantity");
                 total = rs.getString("total");
                 s.displayStockData(pId);
                 pname = s.name;
                 model.insertRow( model.getRowCount(), new Object[]{no,pname,pId,quantity,total});
             }
             
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "Error Loading database!");
        }
        finally
        {
                try 
                {
                    rs.close();
                    ps.close();
                    con.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(Inbox_frame.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel deliveredL;
    private javax.swing.JTextField deliveredTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minusB;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton plusB;
    private javax.swing.JLabel productCodeL;
    private javax.swing.JPasswordField productNoTF;
    private javax.swing.JButton saveB;
    private javax.swing.JButton searchB;
    private javax.swing.JLabel totalPriceL;
    private javax.swing.JTextField totalPriceTF;
    // End of variables declaration//GEN-END:variables
}
