import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class IMS_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form IMS_SignUp
     */
     public static String name,lname="",address,date,email,contact_no,gender,username,password,e_name,access,e_contact,e_email,e_relation,e_address,date_created;
     private Connection con =null;
     private PreparedStatement ps = null;
     private ResultSet rs = null;
    public IMS_SignUp() {
        initComponents();
        con = MySqlConnect.ConnectDB();
           DateFormat timeFormat = new SimpleDateFormat("yyyy-MM-dd");
        
         ActionListener timerListener = new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
               
                Date date = new Date();
               
                date_created  =timeFormat.format(date);
                
            
            }
        };
        Timer timer = new Timer(1000, timerListener);
        // to make sure it doesn't wait one second at the start
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpPanel = new javax.swing.JPanel();
        emailL = new javax.swing.JLabel();
        contactL = new javax.swing.JLabel();
        addressL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        contactTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTF = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        emergencyPanel = new javax.swing.JPanel();
        eNameL = new javax.swing.JLabel();
        eContactL = new javax.swing.JLabel();
        eAddressL = new javax.swing.JLabel();
        eEmailL = new javax.swing.JLabel();
        eRelationL = new javax.swing.JLabel();
        saveB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        eNameTF = new javax.swing.JTextField();
        eContactTF = new javax.swing.JTextField();
        eEmailTF = new javax.swing.JTextField();
        eRelationTF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        eAddTF = new javax.swing.JTextArea();
        passwordL = new javax.swing.JLabel();
        confrimPassL = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        confirmPassPF = new javax.swing.JPasswordField();
        genderCB = new javax.swing.JComboBox<>();
        genderL = new javax.swing.JLabel();
        fnameTF = new javax.swing.JTextField();
        fnameL = new javax.swing.JLabel();
        lnameTF = new javax.swing.JLabel();
        LnameTF = new javax.swing.JTextField();
        monthCB = new javax.swing.JComboBox<>();
        dayCB = new javax.swing.JComboBox<>();
        yearTF = new javax.swing.JTextField();
        bdayL = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        signUpPanel.setBackground(new java.awt.Color(204, 204, 204));

        emailL.setText("Email");

        contactL.setText("Contact No.");

        addressL.setText("Address");

        emailTF.setBackground(new java.awt.Color(255, 255, 153));

        contactTF.setBackground(new java.awt.Color(255, 255, 153));

        addressTF.setBackground(new java.awt.Color(255, 255, 153));
        addressTF.setColumns(20);
        addressTF.setRows(5);
        jScrollPane1.setViewportView(addressTF);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("Incase of emergency person to notify");

        emergencyPanel.setBackground(new java.awt.Color(153, 153, 153));

        eNameL.setText("Name");

        eContactL.setText("Contact");

        eAddressL.setText("Address");

        eEmailL.setText("Email");

        eRelationL.setText("Relation");

        saveB.setBackground(new java.awt.Color(255, 255, 153));
        saveB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        saveB.setText("Submit");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        cancelB.setBackground(new java.awt.Color(255, 255, 153));
        cancelB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        eNameTF.setBackground(new java.awt.Color(255, 255, 153));

        eContactTF.setBackground(new java.awt.Color(255, 255, 153));

        eEmailTF.setBackground(new java.awt.Color(255, 255, 153));

        eRelationTF.setBackground(new java.awt.Color(255, 255, 153));

        eAddTF.setBackground(new java.awt.Color(255, 255, 153));
        eAddTF.setColumns(20);
        eAddTF.setRows(5);
        jScrollPane3.setViewportView(eAddTF);

        javax.swing.GroupLayout emergencyPanelLayout = new javax.swing.GroupLayout(emergencyPanel);
        emergencyPanel.setLayout(emergencyPanelLayout);
        emergencyPanelLayout.setHorizontalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emergencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emergencyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelB))
                    .addGroup(emergencyPanelLayout.createSequentialGroup()
                        .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eContactL)
                            .addComponent(eRelationL)
                            .addComponent(eNameL)
                            .addComponent(eEmailL))
                        .addGap(25, 25, 25)
                        .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eNameTF)
                            .addComponent(eContactTF, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(eEmailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(eRelationTF, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(169, 169, 169)
                        .addComponent(eAddressL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGap(44, 44, 44))
        );
        emergencyPanelLayout.setVerticalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencyPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emergencyPanelLayout.createSequentialGroup()
                        .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(emergencyPanelLayout.createSequentialGroup()
                                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eNameL)
                                    .addComponent(eNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eContactL)
                                    .addComponent(eContactTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eEmailL)
                                    .addComponent(eEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(eAddressL))
                        .addGap(18, 18, 18)
                        .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eRelationL)
                            .addComponent(eRelationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelB)
                    .addComponent(saveB))
                .addGap(20, 20, 20))
        );

        passwordL.setText("Password");

        confrimPassL.setText("Re-enter New password");

        passwordPF.setBackground(new java.awt.Color(255, 255, 153));

        confirmPassPF.setBackground(new java.awt.Color(255, 255, 153));

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", " " }));

        genderL.setText("Gender");

        fnameTF.setBackground(new java.awt.Color(255, 255, 153));

        fnameL.setText("Firstname");

        lnameTF.setText("Lastname");

        LnameTF.setBackground(new java.awt.Color(255, 255, 153));

        monthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " ", " " }));

        dayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        yearTF.setBackground(new java.awt.Color(255, 255, 153));
        yearTF.setText("2017");
        yearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTFActionPerformed(evt);
            }
        });

        bdayL.setText("Birthdate");

        usernameL.setText("username");

        usernameTF.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emergencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1)
                        .addGroup(signUpPanelLayout.createSequentialGroup()
                            .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailL)
                                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(contactL, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fnameL))))
                                .addGroup(signUpPanelLayout.createSequentialGroup()
                                    .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lnameTF)
                                        .addComponent(bdayL))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signUpPanelLayout.createSequentialGroup()
                                        .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dayCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yearTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signUpPanelLayout.createSequentialGroup()
                                        .addComponent(LnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(241, 241, 241)))
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confrimPassL)
                                    .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                            .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(passwordL))
                                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                            .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(180, 180, 180)
                                            .addComponent(addressL)))
                                    .addComponent(usernameL)))))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(genderL)
                        .addGap(18, 18, 18)
                        .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(passwordPF)
                    .addComponent(confirmPassPF)
                    .addComponent(usernameTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameTF)
                            .addComponent(LnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameL)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordL)
                            .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confrimPassL)
                            .addComponent(confirmPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bdayL)
                        .addGap(18, 18, 18)))
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressL)
                            .addComponent(contactL)
                            .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderL)
                            .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emergencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        // TODO add your handling code here:
        if(fnameTF.getText().isEmpty()||lnameTF.getText().isEmpty()||emailTF.getText().isEmpty()||passwordPF.getText().isEmpty()||confirmPassPF.getText().isEmpty()||
                contactTF.getText().isEmpty()||addressTF.getText().isEmpty()||eNameTF.getText().isEmpty()||eContactTF.getText().isEmpty()||eEmailTF.getText().isEmpty()||
                eRelationTF.getText().isEmpty()||eAddTF.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Please fill-up all the missing fields");
        }
        else{
             int a =JOptionPane.showConfirmDialog(null,"Save Changes?","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

               if(a ==0){
                 
                 
                      try {
             // TODO add your handling code here:
            
                             name = fnameTF.getText();
                             lname = LnameTF.getText();
                             address = addressTF.getText();
                             int month = monthCB.getSelectedIndex()+1;
                             date = ""+yearTF.getText()+"-"+month+"-"+dayCB.getSelectedItem().toString();
                             email = emailTF.getText();
                             contact_no = contactTF.getText();
                             gender = genderCB.getSelectedItem().toString();
                             username = usernameTF.getText();
                             password = passwordPF.getText();
                             e_name = eNameTF.getText();
                             access = "inactive";
                             e_contact = eContactTF.getText();
                             e_email = eEmailTF.getText();
                             e_relation = eRelationTF.getText();
                             e_address = eAddTF.getText();
                 
                 
                            String sql = "insert into employee(LastName,FirstName,Address,access,bday,email,contact_no,gender,username,"
                            + "password,e_name,e_contact,e_email,e_relation,e_address,date_created)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                            ps = con.prepareStatement(sql);
                            ps.setString(1,lname);
                            ps.setString(2,name);
                            ps.setString(3,address);
                            ps.setString(4,access);
                            ps.setString(5,date);
                            ps.setString(6,email);
                            ps.setString(7,contact_no);
                            ps.setString(8,gender);
                            ps.setString(9,username);
                            ps.setString(10,password);
                            ps.setString(11,e_name);
                            ps.setString(12,e_contact);
                            ps.setString(13,e_email);  
                            ps.setString(14,e_relation);
                            ps.setString(15,e_address);
                            ps.setString(16,date_created);
                            ps.execute();
                            JOptionPane.showMessageDialog(null, "Data Saved!");
                            JOptionPane.showMessageDialog(null,"Registration sent! please contact admin to verify your account");
             
                 } catch (SQLException ex) {
                     
                         JOptionPane.showMessageDialog(null, "error saving!");
                 }
        
        
        
    } 
                 
                 
                    
                 
                  setVisible(false);
              
             }
       
    }//GEN-LAST:event_saveBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
         if(fnameTF.getText().length()>0||lnameTF.getText().length()>0||emailTF.getText().length()>0||passwordPF.getText().length()>0||confirmPassPF.getText().length()>0||
                contactTF.getText().length()>0||addressTF.getText().length()>0||eNameTF.getText().length()>0||eContactTF.getText().length()>0||eEmailTF.getText().length()>0||
                eRelationTF.getText().length()>0||eAddTF.getText().length()>0){
             
             int a =JOptionPane.showConfirmDialog(null,"All unsaved data will be lost","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

                if(a ==0)
                  {
                    
                     setVisible(false);
                   }
                
              }
           else
              setVisible(false);
    }//GEN-LAST:event_cancelBActionPerformed

    private void yearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTFActionPerformed
 
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LnameTF;
    private javax.swing.JLabel addressL;
    private javax.swing.JTextArea addressTF;
    private javax.swing.JLabel bdayL;
    private javax.swing.JButton cancelB;
    private javax.swing.JPasswordField confirmPassPF;
    private javax.swing.JLabel confrimPassL;
    private javax.swing.JLabel contactL;
    private javax.swing.JTextField contactTF;
    private javax.swing.JComboBox<String> dayCB;
    private javax.swing.JTextArea eAddTF;
    private javax.swing.JLabel eAddressL;
    private javax.swing.JLabel eContactL;
    private javax.swing.JTextField eContactTF;
    private javax.swing.JLabel eEmailL;
    private javax.swing.JTextField eEmailTF;
    private javax.swing.JLabel eNameL;
    private javax.swing.JTextField eNameTF;
    private javax.swing.JLabel eRelationL;
    private javax.swing.JTextField eRelationTF;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JPanel emergencyPanel;
    private javax.swing.JLabel fnameL;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JLabel genderL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lnameTF;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JButton saveB;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables

}
