
import java.util.Date;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Basti
 */
public class IMS_UserForm extends javax.swing.JFrame {

    /**
     * Creates new form IMS_UserForm
     */
     
     IMS_UserLogin s = new IMS_UserLogin();
    public IMS_UserForm() {
        initComponents();
         displayNameL.setText(" "+s.name+" "+s.lname);
         displayEmpNoL.setText(" "+s.id);
         setTitle("INVENTORY MANAGEMENT SYSTEM");
         setLocationRelativeTo(null);
         DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
         DateFormat fullDf = DateFormat.getDateInstance(DateFormat.FULL);
         ActionListener timerListener = new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
               
                Date date = new Date();
                String d = fullDf.format(new Date());
                String t =timeFormat.format(date);
                timeL.setText(t);
                dateL.setText(d);
               
                
            }
        };
        Timer timer = new Timer(1000, timerListener);
        // to make sure it doesn't wait one second at the start
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerP = new javax.swing.JPanel();
        avatarL = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        empNoL = new javax.swing.JLabel();
        displayNameL = new javax.swing.JLabel();
        displayEmpNoL = new javax.swing.JLabel();
        logoutL = new javax.swing.JLabel();
        logoutB = new javax.swing.JLabel();
        mainFormP = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        orderB = new javax.swing.JButton();
        invoiceB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stockB = new javax.swing.JButton();
        dateL = new javax.swing.JLabel();
        timeL = new javax.swing.JLabel();
        mainDP = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1486, 740));

        headerP.setBackground(new java.awt.Color(255, 255, 255));
        headerP.setBorder(new javax.swing.border.MatteBorder(null));

        avatarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar.png"))); // NOI18N

        nameL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nameL.setText("Name:");

        empNoL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        empNoL.setText("Employee No:");

        displayNameL.setText("Sebasthian Pacudan");

        displayEmpNoL.setText("201402510");

        logoutL.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        logoutL.setText("Logout");

        logoutB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logoutB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBMouseClicked(evt);
            }
        });

        mainFormP.setBackground(new java.awt.Color(153, 153, 153));
        mainFormP.setBorder(new javax.swing.border.MatteBorder(null));

        menuPanel.setBackground(new java.awt.Color(255, 255, 153));
        menuPanel.setBorder(new javax.swing.border.MatteBorder(null));

        orderB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telephone.png"))); // NOI18N
        orderB.setText("Add Item");
        orderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBActionPerformed(evt);
            }
        });

        invoiceB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verification-of-delivery-list-clipboard-symbol.png"))); // NOI18N
        invoiceB.setText("Invoice");
        invoiceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        stockB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commerce.png"))); // NOI18N
        stockB.setText("Stock");
        stockB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderB, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(stockB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderB)
                .addGap(18, 18, 18)
                .addComponent(invoiceB)
                .addGap(18, 18, 18)
                .addComponent(stockB)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        dateL.setText("MM/DD/YYYY");

        timeL.setText("HH:MM:SS");

        mainDP.setBackground(new java.awt.Color(153, 153, 153));
        mainDP.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout mainDPLayout = new javax.swing.GroupLayout(mainDP);
        mainDP.setLayout(mainDPLayout);
        mainDPLayout.setHorizontalGroup(
            mainDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDPLayout.setVerticalGroup(
            mainDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainFormPLayout = new javax.swing.GroupLayout(mainFormP);
        mainFormP.setLayout(mainFormPLayout);
        mainFormPLayout.setHorizontalGroup(
            mainFormPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFormPLayout.createSequentialGroup()
                .addGroup(mainFormPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFormPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainFormPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateL)
                            .addComponent(timeL)))
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDP))
        );
        mainFormPLayout.setVerticalGroup(
            mainFormPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFormPLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFormPLayout.createSequentialGroup()
                .addComponent(mainDP)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout headerPLayout = new javax.swing.GroupLayout(headerP);
        headerP.setLayout(headerPLayout);
        headerPLayout.setHorizontalGroup(
            headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPLayout.createSequentialGroup()
                .addComponent(avatarL)
                .addGap(39, 39, 39)
                .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerPLayout.createSequentialGroup()
                        .addComponent(nameL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayNameL))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerPLayout.createSequentialGroup()
                        .addComponent(empNoL)
                        .addGap(18, 18, 18)
                        .addComponent(displayEmpNoL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1033, Short.MAX_VALUE)
                .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutB)
                    .addGroup(headerPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(logoutL)))
                .addGap(37, 37, 37))
            .addComponent(mainFormP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPLayout.setVerticalGroup(
            headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPLayout.createSequentialGroup()
                .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatarL)
                    .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameL)
                                .addComponent(displayNameL))
                            .addGap(18, 18, 18)
                            .addGroup(headerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(empNoL)
                                .addComponent(displayEmpNoL))
                            .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPLayout.createSequentialGroup()
                            .addComponent(logoutB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(logoutL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainFormP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBActionPerformed
        // TODO add your handling code here:
        Stock_frame stock = new Stock_frame();

        this.mainDP.add(stock);
        stock.show();
    }//GEN-LAST:event_stockBActionPerformed

    private void invoiceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBActionPerformed
        // TODO add your handling code here:

        Invoice_form invoice = new Invoice_form();

        this.mainDP.add(invoice);
        invoice.show();
    }//GEN-LAST:event_invoiceBActionPerformed

    private void orderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBActionPerformed
        Order_frame order = new Order_frame();

        this.mainDP.add(order);
        order.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_orderBActionPerformed

    private void logoutBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBMouseClicked
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"LOGOUT?","INVENTORY MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION);

        if(a ==0){
            setVisible(false);
            IMS_UserLogin s = new IMS_UserLogin();
            s.setVisible(true);

        }

    }//GEN-LAST:event_logoutBMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarL;
    private javax.swing.JLabel dateL;
    private javax.swing.JLabel displayEmpNoL;
    private javax.swing.JLabel displayNameL;
    private javax.swing.JLabel empNoL;
    private javax.swing.JPanel headerP;
    private javax.swing.JButton invoiceB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoutB;
    private javax.swing.JLabel logoutL;
    private javax.swing.JDesktopPane mainDP;
    private javax.swing.JPanel mainFormP;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel nameL;
    private javax.swing.JButton orderB;
    private javax.swing.JButton stockB;
    private javax.swing.JLabel timeL;
    // End of variables declaration//GEN-END:variables
}
